# ======================================================================
# Makefile 
# for test
# ======================================================================
#

SOURCES = bbmatch.scm
MAIN = bbmatch-test.scm
EXE = bbmatch-test
CSCFLAGS = -include-path ../sl-printf -include-path ../tester -R chicken-syntax

include ../../mk/app.mk
